name: ArduPilot SITL Validation

on:
  push:
  pull_request:

jobs:
  sitl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip build-essential ccache \
            libtool libxml2-dev libxslt1-dev python3-setuptools \
            python3-opencv python3-dev python3-numpy \
            g++ pkg-config protobuf-compiler libprotobuf-dev \
            libgoogle-glog-dev libgflags-dev screen pipx

          python3 -m pip install empy==3.3.4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Clone ArduPilot and build SITL
        run: |
          git clone --recursive https://github.com/ArduPilot/ardupilot.git
          cd ardupilot
          Tools/environment_install/install-prereqs-ubuntu.sh -y
          . ~/.profile
          ./waf configure --board MatekH743
          ./waf copter
          cd ..
          sudo apt-get install python3-dev python3-opencv python3-wxgtk4.0 python3-pip python3-matplotlib python3-lxml python3-pygame
          python3 -m pip install PyYAML mavproxy --user
          sudo python3 -m pip install wxPython
          sudo python3 -m pip install gnureadline
          sudo python3 -m pip install billiard
          sudo python3 -m pip install numpy pyparsing
          sudo python3 -m pip install MAVProxy

      - name: Run ArduCopter SITL (background)
        run: |
          .ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter --model + --no-mavproxy --start --home=33.7713180251761,-117.69482206241825,0,0 > sitl.log 2>&1 &
          sleep 10
          sleep 480
          cat sitl.log

      - name: Run validation script
        run: |
          poetry run python validate.py
