name: ArduPilot SITL Validation

on:
  push:
  pull_request:

jobs:
  sitl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip build-essential ccache \
            libtool libxml2-dev libxslt1-dev python3-setuptools \
            python3-opencv python3-dev python3-numpy \
            g++ pkg-config protobuf-compiler libprotobuf-dev \
            libgoogle-glog-dev libgflags-dev screen pipx empy

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Install pymavlink (if not in pyproject)
        run: |
          poetry run pip install pymavlink

      - name: Clone ArduPilot and build SITL
        run: |
          git clone --recursive https://github.com/ArduPilot/ardupilot.git
          cd ardupilot
          ./waf configure --board sitl
          ./waf copter

      - name: Run ArduCopter SITL (background)
        run: |
          cd ardupilot
          ./build/sitl/bin/arducopter -S --model quad --home 37.7749,-122.4194,10,270 > sitl.log 2>&1 &
          sleep 10

      - name: Run validation script
        run: |
          poetry run python validate.py
