name: ArduPilot SITL Validation

on:
  push:
  pull_request:

jobs:
  sitl-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run Simulation (wait)
        run: |
          ~/sim_setup.sh
          sleep 60


