name: ArduPilot SITL Validation

on:
  push:
  pull_request:

jobs:
  sitl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip build-essential ccache \
            libtool libxml2-dev libxslt1-dev python3-setuptools \
            python3-opencv python3-dev python3-numpy \
            g++ pkg-config protobuf-compiler libprotobuf-dev \
            libgoogle-glog-dev libgflags-dev screen pipx

          python3 -m pip install empy==3.3.4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Clone ArduPilot and build SITL
        run: |
          git clone --recursive https://github.com/ArduPilot/ardupilot.git
          cd ardupilot
          Tools/environment_install/install-prereqs-ubuntu.sh -y
          . ~/.profile
          ./waf configure --board MatekH743
          ./waf copter
          cd ..

      - name: Run ArduCopter SITL (background)
        run: |
          ./ardupilot/Tools/autotest/sim_vehicle.py -v copter --console --map -w -l 33.7713180251761,-117.69482206241825,0.0,0.0 > sitl.log 2>&1 &
          sleep 480
          cat sitl.log

      - name: Run validation script
        run: |
          poetry run python validate.py
