name: ArduPilot SITL Validation

on:
  push:
  pull_request:

jobs:
  sitl-test:
    runs-on: labpc2
    steps:
      - uses: actions/checkout@v3

      - name: Run Simulation
        run: |
          sim_vehicle.py -v copter --console --map -w -l 33.7713180251761,-117.69482206241825,0.0,0.0


